server:
  port: 8080
spring:
  application:
    name: secondhand-register

  cloud:
    config:
      discovery:
        enabled=true:eureka:
  client:
    service-url:
      defaultZone: http://116.62.125.141:8080/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
ribbon:
  eureka:
    enabled: true

