server:
  port: 8080
spring:
  application:
    name: secondhand-register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000