server:
  port: 9090
spring:
  application:
    name: project-service
  datasource:
    url: jdbc:mysql:///campususeddeals?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8080/eureka
mybatis:
  type-aliases-package: com.secondhand.project.pojo